apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  labels:
    app: express-pipeline
    app.kubernetes.io/instance: express-pipeline-instance
    app.kubernetes.io/name: express-pipeline
  name: express-pipeline
spec:
  params: 
    - name: source-repo
      type: string 
      description: Source code repo 
    - name: commit 
      type: string 
      description: The precise SHA of the most recent commit 
      default: ""
    - name: image-repo 
      type: string 
      description: Docker image name
    - name: app-name 
      type: string 
      description: Application name
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  tasks:
    - name: clone-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.source-repo)"
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: npm-tests
      taskRef:
        kind: Task
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: PATH_CONTEXT
          value: "DISTROLESS-EXPRESS"
        - name: ARGS
          value:
            - install
            - test
      runAfter:
        - clone-repository
    - name: build-image
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces: 
        - name: source
          workspace: pipeline-shared-data
      runAfter:
        - npm-tests
      params:
        - name: IMAGE
          value: "quay.io/alex_best_ibm/the-best-group-4-project-next:$(tasks.clone-repository.results.commit)"
    - name: kustomize
      taskRef:
        kind: Task
        name: kustomize
      runAfter:
        - build-image
      params:
        - name: source-repo
          value: "$(params.source-repo)"
        - name: commit
          value: "$(tasks.clone-repository.results.commit)"
        - name: app-name
          value: "$(params.app-name)"
        - name: app-namespace
          value: "$(context.pipelineRun.namespace)"
        - name: image-repo
          value: "$(params.image-repo)"
      workspaces: 
        - name: source
          workspace: pipeline-shared-data
    - name: try-to-deploy
      taskRef:
        kind: Task
        name: try-to-deploy
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: app-namespace
          value: "$(context.pipelineRun.namespace)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      runAfter:
        - kustomize
    - name: gitops
      taskRef:
        kind: Task
        name: commit-manifest
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: sha
          value: "$(tasks.clone-repository.results.commit)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      runAfter:
        - try-to-deploy

      